### ISSUE TITLE
Can we use Firestore for transport?

### ISSUE THREAD

**Issue by tocteman** [delucis/bgio-firebase#67]
Good evening, 

I'm using this plugin and it's working beautifully, thanks a lot for that.
I was wondering if it would be feasible to use Firestore real-time capabilities as a replacement for Socket-IO and use it as the game transport. Do you think it's possible? If so, what files do you recommend for me to tinker? 

Thanks again!

Best,

juan francisco

**Comment by delucis** [comment]
Hey! I’ve thought about this before — it’s definitely possible in theory, although there are a few things I’m unsure of.

You’d need to implement a client-side transport for this, so you’d need to implement something similar to [boardgame.io’s `Local` transport](https://github.com/boardgameio/boardgame.io/blob/master/src/client/transport/local.ts), using the `firebase` package instead of the server-side `firebase-admin` this storage plugin uses. The local transport runs a game master in the browser instead of expecting one on the server. I imagine the transport would do something like create a Snapshot Listener on connect, write to Firestore on game actions, and call back to the client when it receives updates from the listener.

The more difficult question would be how to manage security. Duplicating lots of game logic into security rules seems impractical for everything except the most simple game, so you wouldn’t be able to prevent cheating in the same way an authoritative server allows. If it’s a 1-player game or only for casual play among friends, that might be acceptable though!

**Comment by tocteman** [comment]
Hello Chris. I had not thought about that. I'll go the socket.io route for now, but will update if we eventually get back to this transport method. 

Thanks a lot!
